error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;

    server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name ydembele.42.fr;

        ssl_certificate     /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        ssl_protocols TLSv1.2 TLSv1.3;

        root /var/www/html/wordpress;
        index index.php index.html;

        error_log /var/log/nginx/error_web.log;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # PHP handling
        location ~ \.php$ {
            include fastcgi_params;

            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_index index.php;

            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

            fastcgi_pass wordpress:9000;
        }

        # protection fichiers cachés
        location ~ /\. {
            deny all;
        }
    }
}